/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul3;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ASUS
 */
public class Perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form Perpustakaan
     */
    String Penulis;
    String Penerbit;
    String TahunTerbit;
    
    public Perpustakaan() {
        initComponents();
    }
    //metode yang digunakan untuk menampilkan gambar pada label dalam GUI
    public void setImage(String Gambar, JLabel Label, int width, int height){
        ImageIcon Cover1 = new ImageIcon(getClass().getResource(Gambar));
        Image cover1 = Cover1.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH ); 
        img1.setIcon(new ImageIcon(cover1));
    }
    //metode yang digunakan untuk menetapkan keterangan yg ingin ditampilkan
    public void setKeterangan(String judul,String Penulis, String Penerbit,String TahunTerbit){
        
        lbPenulis.setText(Penulis);
        lbPenerbit.setText(Penerbit);
        lbTahun.setText(TahunTerbit);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        bLaskar = new javax.swing.JButton();
        bAac = new javax.swing.JButton();
        bBumi = new javax.swing.JButton();
        bPerahu = new javax.swing.JButton();
        bNegeri = new javax.swing.JButton();
        bCinta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        img1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbPenulis = new javax.swing.JLabel();
        lbPenerbit = new javax.swing.JLabel();
        lbTahun = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(371, 60));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PERPUSTAKAAN TRUNOJOYO");

        jLabel6.setText("Jl. Raya Telang, Kamal - Bangkalan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(160, 207));
        jPanel3.setLayout(new java.awt.GridLayout(0, 1, 0, 3));

        bLaskar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bLaskar.setText("LASKAR PELANGI");
        bLaskar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLaskarActionPerformed(evt);
            }
        });
        jPanel3.add(bLaskar);

        bAac.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bAac.setText("AYAT - AYAT CINTA");
        bAac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAacActionPerformed(evt);
            }
        });
        jPanel3.add(bAac);

        bBumi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bBumi.setText("BUMI MANUSIA");
        bBumi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBumiActionPerformed(evt);
            }
        });
        jPanel3.add(bBumi);

        bPerahu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bPerahu.setText("PERAHU KERTAS");
        bPerahu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPerahuActionPerformed(evt);
            }
        });
        jPanel3.add(bPerahu);

        bNegeri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bNegeri.setText("NEGERI 5 MENARA");
        bNegeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNegeriActionPerformed(evt);
            }
        });
        jPanel3.add(bNegeri);

        bCinta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bCinta.setText("CINTA DALAM GELAS");
        bCinta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCintaActionPerformed(evt);
            }
        });
        jPanel3.add(bCinta);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        img1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel2.setText("PENULIS             : ");

        jLabel4.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel4.setText("PENERBIT          :");

        jLabel5.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabel5.setText("TAHUN TERBIT :");

        lbPenulis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        lbTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(10, 10, 10)
                        .addComponent(lbPenulis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lbTahun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lbPenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(lbTahun, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2158, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLaskarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLaskarActionPerformed
         setImage("laskar pelangi.jpeg", img1, img1.getWidth(), img1.getHeight());
         setKeterangan("Laskar Pelangi", "Andrea Hinata", "Bentang Pustaka", "2005");
         
    }//GEN-LAST:event_bLaskarActionPerformed

    private void bAacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAacActionPerformed
        setImage("aac.jpeg", img1, img1.getWidth(), img1.getHeight());
         setKeterangan("Ayat-ayat Cinta", "Habiburrahman El Shirazy", "Republika", "2004");

    }//GEN-LAST:event_bAacActionPerformed

    private void bCintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCintaActionPerformed
        setImage("cintagelas.jpeg", img1, img1.getWidth(), img1.getHeight());
         setKeterangan("Cinta didalam Gelas", "Andrea Hinata", "Bentang Pustaka", "2004");
    }//GEN-LAST:event_bCintaActionPerformed

    private void bBumiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBumiActionPerformed
        setImage("bumi.jpeg", img1, img1.getWidth(), img1.getHeight());
        setKeterangan("Bumi Manusia", "Pramoedya A T", "Hasta Mitra", "1980");

    }//GEN-LAST:event_bBumiActionPerformed

    private void bPerahuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPerahuActionPerformed
        setImage("perahu.jpeg", img1, img1.getWidth(), img1.getHeight());
         setKeterangan("Perahu Kertas", "Dee Lestari", "Bentang Pustaka", "2009");

    }//GEN-LAST:event_bPerahuActionPerformed

    private void bNegeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNegeriActionPerformed
        setImage("negeri.jpeg", img1, img1.getWidth(), img1.getHeight());
         setKeterangan("Negeri 5 Menara", "Ahmad Fuadi", "Gramedia", "2009");

    }//GEN-LAST:event_bNegeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAac;
    private javax.swing.JButton bBumi;
    private javax.swing.JButton bCinta;
    private javax.swing.JButton bLaskar;
    private javax.swing.JButton bNegeri;
    private javax.swing.JButton bPerahu;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbPenerbit;
    private javax.swing.JLabel lbPenulis;
    private javax.swing.JLabel lbTahun;
    // End of variables declaration//GEN-END:variables
}
